[package]
name = "gtk-lock-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.8.1"
pam = "0.8.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
wayland-client = "0.31.2"
wayland-protocols = { version = "0.31.2", features = ["client", "staging", "unstable"] }
wayland-protocols-wlr = { version = "0.2.0", features = ["client"] }
