[package]
name = "gtk-lock-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pam = "0.8.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
smithay-client-toolkit = "0.19.1"
xkbcommon-rs = { version = "0.1.0", features = ["client"] }

